import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-terms-conditions',
  templateUrl: './terms-conditions.component.html',
  styleUrls: ['./terms-conditions.component.css']
})
export class TermsConditionsComponent implements OnInit {
  conditions: any[];
  constructor() { }

  ngOnInit() {
    this.conditions = [
      {heading: "Trxade “DelivMeds” Terms of Use", text: "Please read this document carefully. It contains very important information regarding your rights and obligations, including limitations and exclusions that might apply to you."},
      {heading: "SUMMARYOF TERMS", text: "All use of the application DelivMeds, the “Services,” and/or connected websites and subdomains (unitedly, the “App”) provided by Trxade, Inc., Trxade Group, Inc., and/or Alliance Pharma Solutions, LLC (“we” or “us”) by you on behalf of yourself and/or the patient is subject to the privacy policy located at     delivmeds.com and these “Terms of Use,” all of which are deemed a part of and included within these terms and conditions (collectively, the “Terms”). By using the App, you are acknowledging that you have read, understand, and agree to be bound by the Terms. We reserve the right to adjust, replace, add or remove portions of the Terms at any time for any reason. Modification and variations shall be effective immediately upon posting. When accessing the App after changes have been made, you confirm that you are agreeing to the modification."},

      {heading: "ELECTRONIC COMMUNICATIONS", text: "You agree that DelivMeds and any “Licensed Pharmacy” has permission to contact you or the patient via email, SMS or phone at the contact information you provide at the time of registering. Information transmitted via SMS and email contains personal information about your prescriptions, treatment or      benefits, and individuals with access to your mobile phone, carrier account or email address will also be able to see this information.", textLine: "You may stop receiving email or text alerts by calling DelivMeds at 844-251-4691."},

      {heading: "CONTACT", text: "You agree to be contacted by the Licensed Pharmacies and/or DelivMeds at the contact information provided when installing the App. You must confirm your prescription and scheduling the delivery of      your prescribed medication.", textLine: "BY USING THE DELIVMEDS APP YOU AGREE TO RECEIVE EMAIL, AND/OR SMS MESSAGE      NOTIFICATIONS"},
      {heading: "TRANSFERRING YOUR PRESCRIPTIONS", text: "By signing up to use the DelivMeds app, you agree to permit any Licensed Pharmacy to request the transfer of your prescriptions from the pharmacy where the prescription was riginally sent to by your healthcare provider."},
      {heading: "USER RESPONSIBILITIES", text: "Services provided by the DelivMeds app are currently at no charge, and any cost involved will be included prescriptions you receive from a Licensed Pharmacy. You are responsible for the release of your personal information on the DelivMeds app if you give access of your mobile phone to another person or entity not listed as a patient on the app."},
      {heading: "NO PHARMACY-PATIENT RELATIONSHIP", text: "DelivMeds is not a pharmacy and does not assure availability of any medication. The individual pharmacy controls the inventory; we will not be liable for any cancellation or unfulfilled orders."},
      {heading: "Trxade “DelivMeds” Terms of Use", text: "Please read this document carefully. It contains very important information regarding your rights and obligations, including limitations and exclusions that might apply to you."},
      {heading: "SUMMARYOF TERMS", text: "All use of the application DelivMeds, the “Services,” and/or connected websites and subdomains (unitedly, the “App”) provided by Trxade, Inc., Trxade Group, Inc., and/or Alliance Pharma Solutions, LLC (“we” or “us”) by you on behalf of yourself and/or the patient is subject to the privacy policy located at     delivmeds.com and these “Terms of Use,” all of which are deemed a part of and included within these terms and conditions (collectively, the “Terms”). By using the App, you are acknowledging that you have read, understand, and agree to be bound by the Terms. We reserve the right to adjust, replace, add or remove portions of the Terms at any time for any reason. Modification and variations shall be effective immediately upon posting. When accessing the App after changes have been made, you confirm that you are agreeing to the modification."},

      {heading: "ELECTRONIC COMMUNICATIONS", text: "You agree that DelivMeds and any “Licensed Pharmacy” has permission to contact you or the patient via email, SMS or phone at the contact information you provide at the time of registering. Information transmitted via SMS and email contains personal information about your prescriptions, treatment or      benefits, and individuals with access to your mobile phone, carrier account or email address will also be able to see this information.", textLine: "You may stop receiving email or text alerts by calling DelivMeds at 844-251-4691."},

      {heading: "CONTACT", text: "You agree to be contacted by the Licensed Pharmacies and/or DelivMeds at the contact information provided when installing the App. You must confirm your prescription and scheduling the delivery of      your prescribed medication.", textLine: "BY USING THE DELIVMEDS APP YOU AGREE TO RECEIVE EMAIL, AND/OR SMS MESSAGE      NOTIFICATIONS"},
      {heading: "TRANSFERRING YOUR PRESCRIPTIONS", text: "By signing up to use the DelivMeds app, you agree to permit any Licensed Pharmacy to request the transfer of your prescriptions from the pharmacy where the prescription was riginally sent to by your healthcare provider."},
      {heading: "USER RESPONSIBILITIES", text: "Services provided by the DelivMeds app are currently at no charge, and any cost involved will be included prescriptions you receive from a Licensed Pharmacy. You are responsible for the release of your personal information on the DelivMeds app if you give access of your mobile phone to another person or entity not listed as a patient on the app."},
      {heading: "NO PHARMACY-PATIENT RELATIONSHIP", text: "DelivMeds is not a pharmacy and does not assure availability of any medication. The individual pharmacy controls the inventory; we will not be liable for any cancellation or unfulfilled orders."},
      {heading: "Trxade “DelivMeds” Terms of Use", text: "Please read this document carefully. It contains very important information regarding your rights and obligations, including limitations and exclusions that might apply to you."},
      {heading: "SUMMARYOF TERMS", text: "All use of the application DelivMeds, the “Services,” and/or connected websites and subdomains (unitedly, the “App”) provided by Trxade, Inc., Trxade Group, Inc., and/or Alliance Pharma Solutions, LLC (“we” or “us”) by you on behalf of yourself and/or the patient is subject to the privacy policy located at     delivmeds.com and these “Terms of Use,” all of which are deemed a part of and included within these terms and conditions (collectively, the “Terms”). By using the App, you are acknowledging that you have read, understand, and agree to be bound by the Terms. We reserve the right to adjust, replace, add or remove portions of the Terms at any time for any reason. Modification and variations shall be effective immediately upon posting. When accessing the App after changes have been made, you confirm that you are agreeing to the modification."},

      {heading: "ELECTRONIC COMMUNICATIONS", text: "You agree that DelivMeds and any “Licensed Pharmacy” has permission to contact you or the patient via email, SMS or phone at the contact information you provide at the time of registering. Information transmitted via SMS and email contains personal information about your prescriptions, treatment or      benefits, and individuals with access to your mobile phone, carrier account or email address will also be able to see this information.", textLine: "You may stop receiving email or text alerts by calling DelivMeds at 844-251-4691."},

      {heading: "CONTACT", text: "You agree to be contacted by the Licensed Pharmacies and/or DelivMeds at the contact information provided when installing the App. You must confirm your prescription and scheduling the delivery of      your prescribed medication.", textLine: "BY USING THE DELIVMEDS APP YOU AGREE TO RECEIVE EMAIL, AND/OR SMS MESSAGE      NOTIFICATIONS"},
      {heading: "TRANSFERRING YOUR PRESCRIPTIONS", text: "By signing up to use the DelivMeds app, you agree to permit any Licensed Pharmacy to request the transfer of your prescriptions from the pharmacy where the prescription was riginally sent to by your healthcare provider."},
      {heading: "USER RESPONSIBILITIES", text: "Services provided by the DelivMeds app are currently at no charge, and any cost involved will be included prescriptions you receive from a Licensed Pharmacy. You are responsible for the release of your personal information on the DelivMeds app if you give access of your mobile phone to another person or entity not listed as a patient on the app."},
      {heading: "NO PHARMACY-PATIENT RELATIONSHIP", text: "DelivMeds is not a pharmacy and does not assure availability of any medication. The individual pharmacy controls the inventory; we will not be liable for any cancellation or unfulfilled orders."},
      {heading: "Trxade “DelivMeds” Terms of Use", text: "Please read this document carefully. It contains very important information regarding your rights and obligations, including limitations and exclusions that might apply to you."},
      {heading: "SUMMARYOF TERMS", text: "All use of the application DelivMeds, the “Services,” and/or connected websites and subdomains (unitedly, the “App”) provided by Trxade, Inc., Trxade Group, Inc., and/or Alliance Pharma Solutions, LLC (“we” or “us”) by you on behalf of yourself and/or the patient is subject to the privacy policy located at     delivmeds.com and these “Terms of Use,” all of which are deemed a part of and included within these terms and conditions (collectively, the “Terms”). By using the App, you are acknowledging that you have read, understand, and agree to be bound by the Terms. We reserve the right to adjust, replace, add or remove portions of the Terms at any time for any reason. Modification and variations shall be effective immediately upon posting. When accessing the App after changes have been made, you confirm that you are agreeing to the modification."},

      {heading: "ELECTRONIC COMMUNICATIONS", text: "You agree that DelivMeds and any “Licensed Pharmacy” has permission to contact you or the patient via email, SMS or phone at the contact information you provide at the time of registering. Information transmitted via SMS and email contains personal information about your prescriptions, treatment or      benefits, and individuals with access to your mobile phone, carrier account or email address will also be able to see this information.", textLine: "You may stop receiving email or text alerts by calling DelivMeds at 844-251-4691."},

      {heading: "CONTACT", text: "You agree to be contacted by the Licensed Pharmacies and/or DelivMeds at the contact information provided when installing the App. You must confirm your prescription and scheduling the delivery of      your prescribed medication.", textLine: "BY USING THE DELIVMEDS APP YOU AGREE TO RECEIVE EMAIL, AND/OR SMS MESSAGE      NOTIFICATIONS"},
      {heading: "TRANSFERRING YOUR PRESCRIPTIONS", text: "By signing up to use the DelivMeds app, you agree to permit any Licensed Pharmacy to request the transfer of your prescriptions from the pharmacy where the prescription was riginally sent to by your healthcare provider."},
      {heading: "USER RESPONSIBILITIES", text: "Services provided by the DelivMeds app are currently at no charge, and any cost involved will be included prescriptions you receive from a Licensed Pharmacy. You are responsible for the release of your personal information on the DelivMeds app if you give access of your mobile phone to another person or entity not listed as a patient on the app."},
      {heading: "NO PHARMACY-PATIENT RELATIONSHIP", text: "DelivMeds is not a pharmacy and does not assure availability of any medication. The individual pharmacy controls the inventory; we will not be liable for any cancellation or unfulfilled orders."},

    ]
  }

}
